### ISSUE TITLE
Can all code in this repo be now removed?

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Polyjuice#69]
@alemoi please do so if yes

**Comment by warpech** [comment]
But keep the repo for issues

**Comment by alemoi** [comment]
Can one remove and keep issues? "This will permanently delete the StarcounterSamples/Polyjuice repository, wiki, issues, and comments, and remove all team associations."

**Comment by warpech** [comment]
I don't mean remove the repo. I only mean delete the files (except README.md - this file can stay) and push to the repo.

**Comment by warpech** [comment]
Since there is no answer, I assume yes. I will push a change to delete all code and see what happens.
