### ISSUE TITLE
Replace concepts.ring2.vendible in apps

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Polyjuice#71]
Replace the instances of `concepts.ring2.vendible` with appropriate Simplified Product mapping:

- https://github.com/StarcounterSamples/Images/blob/master/src/Images/Api/MainHandlers.cs
- https://github.com/StarcounterSamples/Products/blob/master/src/Products/Api/OntologyHooks.cs
- https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/Api/OntologyHooks.cs
- https://github.com/StarcounterSamples/Procurement/blob/master/src/Procurement/Api/OntologyHooks.cs

**Comment by warpech** [comment]
@miyconst could you do this?

**Comment by miyconst** [comment]
Replaced with `Simplified.Ring3.Product`.
