### ISSUE TITLE
Remove Starcounter.Node reference from demos

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Polyjuice#72]
There is a lot of demos that keep reference to Starcounter.Node, which does no longer exist:

https://github.com/search?utf8=%E2%9C%93&q=user%3Astarcounter+user%3Astarcountersamples+node+filename%3Acsproj&type=Code&ref=searchresults

**Comment by warpech** [comment]
@miyconst could you please do it and rerelease the apps? Might be related to https://github.com/StarcounterSamples/UserAdmin/issues/9

**Comment by warpech** [comment]
@alemoi in what Starcounter version was Starcounter.Node removed?

**Comment by alemoi** [comment]
> @alemoi in what Starcounter version was Starcounter.Node removed?

Was made very long time ago actually, with some applications adopted but not all apparently.
Here it was mentioned: http://starcounter.io/nightly-changes/list-breaking-changes-starting-build-2-1-1-3/

Should not case the problems for https://github.com/StarcounterSamples/UserAdmin/issues/9 however, since all other applications that still reference Starcounter.Node are built fine without errors.

**Comment by miyconst** [comment]
Apps to fix:

- [ ] Starcounter/ProcurementDemo
- [ ] StarcounterSamples/Notes
- [ ] StarcounterSamples/Chatter
- [ ] StarcounterSamples/Billing
- [ ] StarcounterSamples/Noise
- [ ] StarcounterSamples/Skyper
- [ ] Starcounter/Squared
- [ ] StarcounterSamples/Barcodes
- [ ] StarcounterSamples/People
- [ ] StarcounterSamples/Polyjuice
- [ ] StarcounterSamples/Enecto
- [ ] StarcounterSamples/Products
- [ ] StarcounterSamples/Procurement
- [ ] StarcounterSamples/Welcome
- [ ] Starcounter/RetailDemo
- [ ] StarcounterSamples/SelfishApp
- [ ] Starcounter/PolymerBoilerplate
- [ ] StarcounterSamples/microLauncher
- [ ] StarcounterSamples/UsageTracker
- [ ] StarcounterSamples/AppStoreClient
- [ ] Starcounter/TodoDemo
- [ ] StarcounterSamples/MultiplePagesDemo
- [ ] StarcounterSamples/SignIn
- [ ] StarcounterSamples/SysUpgrade
- [ ] Starcounter/PokerDemo
- [ ] StarcounterSamples/GoogleSignIn
- [ ] StarcounterSamples/PuppetDemo

**Comment by miyconst** [comment]
@warpech can this be closed as all current repositories are updated?

**Comment by warpech** [comment]
Yes, thank you!
